services:
  - type: web
    name: wealthwatch
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://joyjames_db_user:luqhq1z77rhXMIAU@cluster0.my6yhev.mongodb.net/wealthwatch?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 10000
